__title__ = 'ReadEm'
__description__ = 'Python HTTP Server for markdown files.'
__url__ = 'https://github.com/jockerz/ReadEm'
__version__ = '1.0.2'
__author__ = 'jockerz'
__author_email__ = 'jockerz@protonmail.com'
__license__ = 'GNU General Public License v3.0'
__copyright__ = 'Copyright 2022 Jockerz'
