__title__ = 'ReadEm'
__description__ = 'Python HTTP Server special for markdown.'
__url__ = 'https://github.com/jockerz/ReadEm'
__version__ = '0.1.6'
__author__ = 'jockerz'
__author_email__ = 'jockerz@protonmail.com'
__license__ = 'GNU General Public License v3.0'
__copyright__ = 'Copyright 2021 Jockerz'
